# Generated by Django 4.1.1 on 2022-09-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceroom',
            name='projector_availability',
            field=models.BooleanField(default=False),
        ),
    ]
